name: Run Cypress Tests

description: Run Cypress tests

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Setup Docker project
      shell: bash
      run: docker compose up -d

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Wait for frontend to be ready
      shell: bash
      run: |
        for i in {1..10}; do
          curl -s http://127.0.0.1:3000 && echo "Frontend is ready" && exit 0
          echo "Waiting for frontend to be ready... attempt $i"
          sleep 1
        done
        echo "Frontend failed to be ready after 10 retries"
        exit 1

    - name: Run Cypress tests
      shell: bash
      run: npm run cy:run

